detect_fire:
  ros__parameters:
    # tuning_mode: false # Could set this here but leave it off so it can be easily set by the launch script
    x_min: 0
    x_max: 100
    y_min: 0
    y_max: 100
    s_min: 0
    s_max: 255
    v_min: 0
    v_max: 255
    sz_min: 7
    sz_max: 100

detect_fire_3d:
  ros__parameters:
    h_fov: 1.089
    fire_radius: 3
    camera_frame: "camera_link_optical"

follow_fire:
  ros__parameters:
    rcv_timeout_secs: 1.0
    angular_chase_multiplier: 0.7
    forward_chase_speed: 0.1
    search_angular_speed: 0.5
    max_size_thresh: 0.1
    filter_value: 0.9